#=========================================================================
# Convert .lib to .db files for synopsys tools
#=========================================================================

name: convert-lib2db

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - design.lib

outputs:
  - design.db

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

commands: 
  - dc_shell-xg-t -64bit -output_log_file build.log -f generate_db.tcl
