#=========================================================================
# Cadence Genus -- Generate .lib
#=========================================================================

name: cadence-genus-genlib

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.vcs.v
  - design.spef.gz
  - design.pt.sdc

outputs:
  - design.lib

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p logs
  - genus -no_gui -f START.tcl -log logs/genus.log
  - mkdir -p outputs && cd outputs
  - ln -sf ../*.lib design.lib

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined
  order:
    - set_libs.tcl
    - read_design.tcl
    - extract_model.tcl

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'genus' )                # tool check
  - assert File( 'inputs/adk' )              # must exist
  - assert File( 'inputs/design.vcs.v' )     # must exist
  - assert File( 'inputs/design.pt.sdc' )    # must exist
# - assert File( 'inputs/design.spef.gz' )   # spef is optional

postconditions:

  - assert File( 'outputs/design.lib' )      # must exist

  # Basic error checking

  - assert 'error' not in File( 'logs/genus.log' )
  - assert 'Unresolved references' not in File( 'logs/genus.log' )
  - assert 'Unable to resolve' not in File( 'logs/genus.log' )
